### ISSUE TITLE
How to use shorthand syntax outside of patternlab itself

### ISSUE THREAD

**Issue by adamf321** [pattern-lab/edition-php-twig-standard#18]
We're building a WordPress starter theme which uses patternlab as a dependency in order for us to work using atomic design.

The idea is to re-use the templates created in patternlab in our theme. However, using the normal twig way of doing things doesn't work as it can't interpret the shorthand syntax (http://patternlab.io/docs/pattern-including.html).

Where is this set in the patternlab twig code? And how can we reuse it outside of patternlab?

Thanks!

PS The theme will be open source and we'd love to share it with the patternlab community!

**Comment by bradfrost** [comment]
Hey @adamf321,
Thanks for your interest in making a Wordpress theme that has Pattern Lab baked in. That sounds fantastic!

> Where is this set in the patternlab twig code? And how can we reuse it outside of patternlab?

I'm not the best person to answer this as I'm a bit outside of the nitty gritty, but perhaps @EvanLovely could share how they did it for the [Drupal edition](https://github.com/pattern-lab/edition-php-drupal-standard)?

**Comment by adamf321** [comment]
Thanks @bradfrost! 

I already discussed it with Dave Olsen in the Gitter room, I think it will all work nicely once we can order patterns without adding the numeration to the name (e.g. 01-my-organism). Until then we'll have to live with it being a bit more messy than I'd like.

Ref https://github.com/pattern-lab/patternlab-php-core/issues/48

**Comment by dmolsen** [comment]
Since it sounds like this one has a solution (albeit not great) I'm closing it.
