### ISSUE TITLE
Could not open input file: core/console

### ISSUE THREAD

**Issue by darylknight** [pattern-lab/edition-php-twig-standard#23]
I've tried installing PatternLab both as a pre-built project and with Composer. Whenever I try to do anything with the command line I get this error:

`Could not open input file: core/console`

What do I need to do to fix this? I'm on Mac OS Sierra, PHP version 5.6.25. MAMP is installed.

**Comment by marineb** [comment]
Having the same issue. Did you figure it out @darylknight?

**Comment by darylknight** [comment]
No, sorry! I gave up and used Fractal instead.

**Comment by marineb** [comment]
Ok thank you, will check it out! (link for others interested http://fractal.build/)

**Comment by guayom** [comment]
I have the same issue. Any ideas?

**Comment by jsheffers** [comment]
This issue is likely due to the directory that you're running the command in.  This command needs to be run within the project directory of pattern-lab itself (whatever directory you created with the composer create-project command).

**Comment by saniphilp** [comment]
I installed the twig edition.
I used the following command 

         npm run serve

I found this in the package.json file.
