### ISSUE TITLE
"pre-built project" problem with "Git for Windows"

### ISSUE THREAD

**Issue by voku** [pattern-lab/edition-php-twig-standard#6]
System: Windows 10
Shell: "Git for Windows" v1.9.5
PHP: v5.5

---

the command I typed:

```
php core/console --generate
```

---

![image](https://cloud.githubusercontent.com/assets/264695/8224456/8ccba7d6-1587-11e5-8a7a-114ea08ce437.png)

**Comment by dmolsen** [comment]
Fixed.
