### ISSUE TITLE
Installation within an existing project?

### ISSUE THREAD

**Issue by cviebrock** [pattern-lab/edition-php-twig-standard#8]
I have an existing project (Laravel-based, if you're curious), and we use Twig templates for our output.

I was hoping to incorporate a styleguide system within my project, with the goal being that my SCSS/CSS and templates exist only in one place and are used for the live site and for the styleguide.

My first step was to run `composer require --dev pattern-lab/edition-twig-standard` in my project (which actually required a bit of jiggling to keep dependencies in check).  Then I thought I could run `php vendor/pattern-lab/edition-twig-standard/core/console ...` to get things going, but all I get is:

```
it doesn't appear that pattern lab has been set-up yet...
please install pattern lab's dependencies by typing: php core/bin/composer.phar install...
```

The problem is that `console` is explictly expecting the _vendor_ directory to be within the package, not the other way around:

``` php
// set-up the project base directory
$baseDir = __DIR__."/../";

// auto-load classes
if (file_exists($baseDir."vendor/autoload.php")) {
    require($baseDir."vendor/autoload.php");
} else {
    print "it doesn't appear that pattern lab has been set-up yet...\n";
    print "please install pattern lab's dependencies by typing: php core/bin/composer.phar install...\n";
    exit;
}
```

I'm sure there is another way to check that dependencies are installed (or simply remove this check, since things will fail anyway which should be indication that the user missed something).

But I'm also wondering whether other things (e.g. configuration) would work in a setup where Patternlab is a required package instead of an app in and of itself.  Has anyone else done something like this?

Thanks!

**Comment by mpdude** [comment]
_bump_, same here. Have you been successful?

**Comment by cviebrock** [comment]
I gave up on Patternlab.  Haven't gotten around to trying anything else either. :(

**Comment by dmolsen** [comment]
I'm not personally going to tackle this. core is a dependency of an edition. An edition is similar to setting up a base Laravel project. For now Pattern Lab is a standalone project that can't easily be included within another. It's a little more complicated than a single dependency. I think several folks are exploring this, especially with Drupal, but it's outside the scope of my own work. Sorry.

**Comment by trevorkjorlien** [comment]
Next month is DrupalCon in New Orleans. This session will explore integrating Pattern Lab within a Drupal project/theme: 

https://events.drupal.org/neworleans2016/sessions/big-easy-front-end-development-pattern-lab-and-twig

I expect some of the concepts from this session could apply to other setups beside Drupal. The sessions are recorded, so if you check this link in about six weeks, it should be there.

**Comment by dmolsen** [comment]
@trevorkjorlien -

Thanks for the heads up. Seems like several people are tackling this issue currently. I've added new maintainers for the Twig material since they're closer to the implementation. I've also created a [Drupal edition repo](https://github.com/pattern-lab/edition-php-drupal-standard) for those folks to play in. We also have [a channel on Gitter](https://gitter.im/pattern-lab/php) that I expect to be driven by discussion of this topic. It was set-up earlier today so it's a little quiet ;)

**Comment by trevorkjorlien** [comment]
The video for the presentation I mentioned is now online here: https://events.drupal.org/neworleans2016/sessions/big-easy-front-end-development-pattern-lab-and-twig

And I also found this a really helpful resource, at least for Drupal: http://www.aleksip.net

So as I mentioned in my comment last month, this probably won't solve the problem directly, but you could draw from the concepts found here for your own projects.

**Comment by dmolsen** [comment]
Thanks for sharing the presentation. I know that someone from that team has joined our Gitter channel. @aleksip is actually a Pattern Lab team member now. Hopefully we're working through many of the issues he's identified to get Pattern Lab working better with Drupal. The original issue is with the autoloader so I guess I can see if he autoloader has already been run before trying to load it again. That's pretty much boilerplate code though. Hopefully you got to see the Phase 2 talk as well. Similar topic.

**Comment by daspete** [comment]
Hi there,

i've started a little project to integrate patternlab to laravel and it kind of works... many things to do... maybe it can be done better.... feedback is very welcome :)

The package can be found here: [patternlab-twig-laravel](https://packagist.org/packages/daspete/patternlab-twig-laravel)

**Comment by dmolsen** [comment]
@daspete -

Thanks for working on that :) If you can [hop on Gitter](https://gitter.im/pattern-lab/php) that'd be great. Lots of discussion there and some folks who have tried embedding the system. Might be able to pick up pointers. Also it's a good way to have voices heard since @bmuenzenmeyer and I are trying to do a better job of laying out a roadmap and synced features via [The Spec](https://github.com/pattern-lab/the-spec) and [a port interop group](https://github.com/pattern-lab/the-spec/blob/draft/PL-PIG.md).
